<template>
  <header>
    <nav>
      <div class="containerNavItems">
        <div class="firstItems">
          <h1>{{ movies.original_title }}</h1>
          <a href="#">icon</a>
        </div>
        <aside class="containerAside">
          <button>Watch</button>
        </aside>
      </div>
    </nav>
    <section>
      <div id="containerBackgroundImage">
        <img
          :src="`https://image.tmdb.org/t/p/original/${movies.backdrop_path}`"
          width="100"
          height="100"
          id="backdropImageMovie"
        />
      </div>
    </section>
    <!-- <div class="castOfTheMovie" v-for="cast in casts" :key="cast.id">
      <h1>This is an about {{ $route.params.id }}</h1>
      <h2>{{ cast.character }} || {{ cast.name }}</h2>
      <img
        :src="`https://image.tmdb.org/t/p/original/${cast.profile_path}`"
        width="100"
        height="100"
        :alt="cast.name"
      />
      <router-link :to="{ name: 'Person', params: { idPerson: cast.id } }">
        see actor
      </router-link>
    </div> -->
  </header>
</template>

<script>
import axios from "axios";
export default {
  data() {
    return {
      casts: "",
      movies: [],
    };
  },
  async mounted() {
    const { id } = this.$route.params;
    const response = await axios.get(
      `https://api.themoviedb.org/3/movie/${id}/credits?api_key=e3c3595204a142ec627688c9ea2ad00f&language=en-US`
    );
    const data = response.data;
    this.casts = data.cast;
  },
  async created() {
    const { id } = this.$route.params;
    const api_key = "e3c3595204a142ec627688c9ea2ad00f";

    const getDetailsMovies = await axios
      .get(
        `https://api.themoviedb.org/3/movie/${id}?api_key=${api_key}&language=en-US`
      )
      .then((response) => {
        const data = response.data;
        this.movies = data;
        console.log(data);
      });
    return getDetailsMovies;
  },
  methods: {},
};
</script>
<style>
nav {
}
.containerNavItems {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: space-between;
  background: yellowgreen;
}
.firstItems {
  display: flex;
  flex: 2;
  justify-content: space-between;
  align-items: center;
  background: gold;
}
.containerAside {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  background: red;
}
.castOfTheMovie {
  width: 600px;
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  align-items: flex-start;
  justify-content: center;
  margin: 0 auto;
}
section {
  width: 100%;
  height: 100%;
}
#containerBackgroundImage {
  width: 100%;
  height: 100%;
}
#backdropImageMovie {
  width: 100%;
  height: 100%;
  background-size: cover;
}
#containerBackgroundImage {
  -webkit-animation: containerBackgroundImage 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: containerBackgroundImage 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
} /* ----------------------------------------------
 * Generated by Animista on 2021-11-12 13:23:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation backdropImageMovie
 * ----------------------------------------
 */
@-webkit-keyframes containerBackgroundImage {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}
@keyframes containerBackgroundImage {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 100% 0%;
    transform-origin: 100% 0%;
    opacity: 1;
  }
}
</style>